# Generated by Django 5.0.1 on 2024-02-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_profesion_empleado_puesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='nombre',
            new_name='nombreArticulo',
        ),
    ]
